"use client";
import Footer from "@/app/_components/Footer";
import Navigation from "@/app/_components/Navigation";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  CartContextProvider,
  CreateCartContext,
} from "./_components/CartProvider";
import "./globals.css";

export const cartContextObject = CreateCartContext();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    height: "device-height",
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider context={cartContextObject}>
          <div className="absolute right-0 -z-10">
            <svg
              width="545"
              height="330"
              viewBox="0 0 545 330"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle
                cx="307"
                cy="23"
                r="282"
                stroke="#F5845D"
                strokeWidth="50"
              />
            </svg>
          </div>
          <div className="z-10">
            <Navigation />
            {children}
            <Footer />
          </div>
        </CartContextProvider>
      </body>
    </html>
  );
}
